# Generated by Django 6.0 on 2025-12-05 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Universities',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Название университета')),
                ('detail_info', models.TextField(verbose_name='Информация')),
                ('university_type', models.CharField(choices=[('technical', 'Технический'), ('medical', 'Медицинский'), ('humanitarian', 'Гуманитарный'), ('creative', 'Творческий')], default='technical', max_length=50, verbose_name='Тип универа')),
                ('ent_score', models.IntegerField(verbose_name='Минимальный балл ент')),
                ('image', models.ImageField(blank=True, null=True, upload_to='', verbose_name='Фото университета')),
            ],
        ),
    ]
